server {
    listen 80;
    server_name saludok.com.ar;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esto redirige todas las peticiones a index.html para que React maneje el ruteo
        try_files $uri $uri/ /index.html;
    }

    # Cache de assets estáticos (opcional pero recomendado)
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}